// AUTO-GENERATED by Scripts/shim-probe.py — do not edit, do not commit.
// One `use` per NS*/CG* symbol grepped from the in-scope Swift files. The compiler,
// not a regex, decides whether swiftshim resolves each one.
#![allow(unused_imports)]

use swiftshim::CGFloat;
use swiftshim::CGGlyph;
use swiftshim::CGPoint;
use swiftshim::CGRect;
use swiftshim::CGSize;
use swiftshim::NSAttributedString;
use swiftshim::NSBezierPath;
use swiftshim::NSBitmapImageRep;
use swiftshim::NSColor;
use swiftshim::NSDataDetector;
use swiftshim::NSEdgeInsets;
use swiftshim::NSFont;
use swiftshim::NSFontDescriptor;
use swiftshim::NSGradient;
use swiftshim::NSImage;
use swiftshim::NSLayoutManager;
use swiftshim::NSMutableAttributedString;
use swiftshim::NSMutableParagraphStyle;
use swiftshim::NSNotFound;
use swiftshim::NSNumber;
use swiftshim::NSObject;
use swiftshim::NSParagraphStyle;
use swiftshim::NSPoint;
use swiftshim::NSRange;
use swiftshim::NSRect;
use swiftshim::NSRectEdge;
use swiftshim::NSRegularExpression;
use swiftshim::NSScrollView;
use swiftshim::NSSize;
use swiftshim::NSString;
use swiftshim::NSTextAlignment;
use swiftshim::NSTextAttachment;
use swiftshim::NSTextBlock;
use swiftshim::NSTextCheckingResult;
use swiftshim::NSTextContainer;
use swiftshim::NSTextStorage;
use swiftshim::NSTextTab;
use swiftshim::NSTextTable;
use swiftshim::NSTextTableBlock;
use swiftshim::NSTextView;
use swiftshim::NSUnderlineStyle;
use swiftshim::NSValue;
use swiftshim::NSView;
use swiftshim::NSWritingDirection;
use swiftshim::NSWritingDirectionFormatType;

fn main() {}
