#!/usr/bin/env python3
"""Compiler-verified symbol-coverage gate for `swiftshim` (docs/plans/rust-port-convention.md §4).

A regex can find `NS*`/`CG*` identifiers in the Swift source; it cannot say whether `swiftshim`
actually resolves them — a comment mentioning `NSString` looks identical to a declaration to
grep. So this script does not judge coverage itself: it greps the in-scope files for candidate
symbols, generates a throwaway `cargo` example that imports every one of them (`use swiftshim::
X;`), and lets `rustc` be the judge. Only `error[E0432]: unresolved import` on that example counts
as a gap; any other build failure (a genuine compile error elsewhere in the crate) is reported
separately and does not get silently absorbed into "coverage".

The generated example is removed after each run — it is a probe, not a fixture.

Usage: python3 Scripts/shim-probe.py
Exit: 0 if every candidate symbol resolves, 1 otherwise (unresolved symbols, or any other
      build failure).
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUST_DIR = ROOT / "rust"
MANIFEST = RUST_DIR / "PORT-MANIFEST.txt"
SWIFT_SRC = ROOT / "Sources" / "FastDocReader"
EXAMPLE_DIR = RUST_DIR / "crates" / "swiftshim" / "examples"
EXAMPLE_NAME = "shim_probe_generated"
EXAMPLE_PATH = EXAMPLE_DIR / f"{EXAMPLE_NAME}.rs"

# Foundation/AppKit-shaped identifiers. Matches things this crate should name (NSColor,
# CGFloat, ...) and, harmlessly, the app's own custom types that happen to start the same way
# (there are none among NS*/CG* in the in-scope files at time of writing) — a false positive
# here just means the probe demands a symbol nothing actually needs, which surfaces as a
# spurious unresolved entry the operator can dismiss by eye, not a silent hole.
SYMBOL_RE = re.compile(r"\b(NS[A-Z][A-Za-z]+|CG[A-Za-z]+)\b")

UNRESOLVED_IMPORT_RE = re.compile(r"error\[E0432\]: unresolved import `swiftshim::(\w+)`")


def in_scope_files() -> list[str]:
    """swift-range: PORT-MANIFEST.txt's non-comment, non-blank lines above the EXCLUDED marker."""
    files = []
    for line in MANIFEST.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        files.append(line)
    return files


def collect_symbols(files: list[str]) -> set[str]:
    symbols: set[str] = set()
    missing: list[str] = []
    for rel in files:
        path = SWIFT_SRC / rel
        if not path.exists():
            missing.append(rel)
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        symbols.update(SYMBOL_RE.findall(text))
    if missing:
        print("warning: PORT-MANIFEST.txt lists files that do not exist on disk:", file=sys.stderr)
        for rel in missing:
            print(f"  {rel}", file=sys.stderr)
    return symbols


def write_example(symbols: set[str]) -> None:
    EXAMPLE_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by Scripts/shim-probe.py — do not edit, do not commit.",
        "// One `use` per NS*/CG* symbol grepped from the in-scope Swift files. The compiler,",
        "// not a regex, decides whether swiftshim resolves each one.",
        "#![allow(unused_imports)]",
        "",
    ]
    lines += [f"use swiftshim::{sym};" for sym in sorted(symbols)]
    lines += ["", "fn main() {}"]
    EXAMPLE_PATH.write_text("\n".join(lines) + "\n")


def remove_example() -> None:
    if EXAMPLE_PATH.exists():
        EXAMPLE_PATH.unlink()
    try:
        EXAMPLE_DIR.rmdir()
    except OSError:
        pass  # not empty — other examples live here; that's fine, only ours is generated


def run_build() -> subprocess.CompletedProcess:
    return subprocess.run(
        ["cargo", "build", "-p", "swiftshim", "--example", EXAMPLE_NAME],
        cwd=RUST_DIR,
        capture_output=True,
        text=True,
    )


def main() -> int:
    files = in_scope_files()
    symbols = collect_symbols(files)
    print(f"in-scope files: {len(files)}")
    print(f"distinct NS*/CG* symbols found by grep: {len(symbols)}")

    write_example(symbols)
    try:
        result = run_build()
    finally:
        remove_example()

    unresolved = sorted(set(UNRESOLVED_IMPORT_RE.findall(result.stderr)))

    if unresolved:
        print(f"UNRESOLVED ({len(unresolved)}) — swiftshim does not export these:")
        for sym in unresolved:
            print(f"  {sym}")
        return 1

    if result.returncode != 0:
        print("build failed for a reason other than an unresolved swiftshim import:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        return 1

    print("all symbols resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
